Add files via upload

diff --git a/antoniovandre_mathgame_linux b/antoniovandre_mathgame_linux
--- a/antoniovandre_mathgame_linux
+++ b/antoniovandre_mathgame_linux
@@ -6,7 +6,7 @@
 
 # Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).
 
-# Última atualização: 25-08-2025. Não considerando alterações em variáveis globais e personalizações.
+# Última atualização: 19-10-2025. Não considerando alterações em variáveis globais e personalizações.
 
 # Argumentos: "ne" para não processar estatísticas, ou "oe" para apenas processar estatísticas.
 
@@ -895,11 +895,11 @@ if [ "${1}" != "ne" ] && [ "${AVLOG}" == "1" ] && [ "${AVGRAFICOS}" == "1" ] && 
 
   echo "2 Erros ${NUMEROERROS} 7" >> "${ARQUIVOGNUPLOTDATA}"
 
-  if [ "${MAXACERTOSERROS}" -gt "0" ]; then gnuplot -p -e "set xtics font 'Verdana,10'; set yrange [0:]; set boxwidth 0.3; set style fill solid; set ytics 0,${MAXACERTOSERROS}; set terminal png size 800,600; set title 'Comparativo de acertos e erros.'; show title; set output '${ARQUIVOGRAFICO}'; plot '${ARQUIVOGNUPLOTDATA}' using 1:3:4:xtic(2) notitle with boxes linecolor variable" &>> /dev/null; else cp "${IMAGEGRAPH0}" "${ARQUIVOGRAFICO}" &>> /dev/null; fi
+  if [ "${MAXACERTOSERROS}" -gt "0" ]; then gnuplot -p -e "set xtics font 'Verdana,10'; set yrange [0:]; set boxwidth 0.3; set style fill solid; set ytics 0,${MAXACERTOSERROS}; set terminal png size 800,600; set title 'Comparativo de acertos e erros - $(date).'; show title; set output '${ARQUIVOGRAFICO}'; plot '${ARQUIVOGNUPLOTDATA}' using 1:3:4:xtic(2) notitle with boxes linecolor variable, '' using 1:(3):3 notitle with labels font 'Verdana,7'" &>> /dev/null; else cp "${IMAGEGRAPH0}" "${ARQUIVOGRAFICO}" &>> /dev/null; fi
 
   echo -ne "\b"; case "${CHARPROGRESS}" in "") CHARPROGRESS="-";; "-") CHARPROGRESS="\\";; "\\") CHARPROGRESS="|";; "|") CHARPROGRESS="/";; "/") CHARPROGRESS="-";; *) ;; esac; echo -ne "${CHARPROGRESS}"
 
-  if [ "${MAXACERTOSERROS}" -gt "0" ]; then gnuplot -p -e "Ai=0.0; yi=0.0; yi2=0.0; ang(x)=x*360.0/${TOTALRESPOSTAS}; set size square; set xrange [-1:1.5]; set yrange [-1.25:1.25]; set boxwidth 0.3; set style fill solid 1; unset border; unset tics; unset key; set terminal png size 800,600; set title 'Comparativo de acertos e erros.'; show title; set output '${ARQUIVOGRAFICOPIZZA}'; plot '${ARQUIVOGNUPLOTDATA}' u (0):(0):(1):(Ai):(Ai=Ai+ang(\$3)):(\$4) with circle linecolor var, '${ARQUIVOGNUPLOTDATA}' u (1.5):(yi=yi+0.5/\$3):(\$2) w labels, '${ARQUIVOGNUPLOTDATA}' u (1.3):(yi2=yi2+0.5/\$3):(\$4) w p pt 5 ps 2 linecolor var" &>> /dev/null; else cp "${IMAGEGRAPH0}" "${ARQUIVOGRAFICOPIZZA}" &>> /dev/null; fi
+  if [ "${MAXACERTOSERROS}" -gt "0" ]; then gnuplot -p -e "Ai=0.0; yi=0.0; yi2=0.0; ang(x)=x*360.0/${TOTALRESPOSTAS}; set size square; set xrange [-1:1.5]; set yrange [-1.25:1.25]; set boxwidth 0.3; set style fill solid 1; unset border; unset tics; unset key; set terminal png size 800,600; set title 'Comparativo de acertos e erros - $(date).'; show title; set output '${ARQUIVOGRAFICOPIZZA}'; plot '${ARQUIVOGNUPLOTDATA}' u (0):(0):(1):(Ai):(Ai=Ai+ang(\$3)):(\$4) with circle linecolor var, '${ARQUIVOGNUPLOTDATA}' u (1.5):(yi=yi+0.5/\$3):(\$2) w labels, '${ARQUIVOGNUPLOTDATA}' u (1.3):(yi2=yi2+0.5/\$3):(\$4) w p pt 5 ps 2 linecolor var" &>> /dev/null; else cp "${IMAGEGRAPH0}" "${ARQUIVOGRAFICOPIZZA}" &>> /dev/null; fi
 
   echo -ne "\b"; case "${CHARPROGRESS}" in "") CHARPROGRESS="-";; "-") CHARPROGRESS="\\";; "\\") CHARPROGRESS="|";; "|") CHARPROGRESS="/";; "/") CHARPROGRESS="-";; *) ;; esac; echo -ne "${CHARPROGRESS}"
 
@@ -1091,27 +1091,27 @@ if [ "${1}" != "ne" ] && [ "${AVLOG}" == "1" ] && [ "${AVGRAFICOS}" == "1" ] && 
 
   ERRMAXHORADIA=$(if [ "${ERRMAXHORADIA}" -lt "10" ]; then echo -n $(expr "${ERRMAXHORADIA}" + 1); else echo "${ERRMAXHORADIA} * 1.1" | bc | cut -d "." -f 1; fi)
 
-  if [ "${MAXDIASEMANA}" -gt "0" ]; then gnuplot -p -e "set xtics font 'Verdana,10'; set yrange [0:${MAXDIASEMANA}]; set boxwidth 0.3; set style fill solid; set terminal png size 800,600; set xtics rotate by 90 right; unset ytics; set title 'Distribuição semanal de uso do game.'; show title; set output '${ARQUIVOGRAFICOTEMPODISTSEM}'; plot '${ARQUIVOGNUPLOTDATA2}' using 2:xticlabels(1) notitle with boxes linecolor rgb \"gray\", '' using 0:2:2 notitle with labels font 'Verdana,7'"  &>> /dev/null; else cp "${IMAGEGRAPH0}" "${ARQUIVOGRAFICOTEMPODISTSEM}" &>> /dev/null; fi
+  if [ "${MAXDIASEMANA}" -gt "0" ]; then gnuplot -p -e "set xtics font 'Verdana,10'; set yrange [0:${MAXDIASEMANA}]; set boxwidth 0.3; set style fill solid; set terminal png size 800,600; set xtics rotate by 90 right; unset ytics; set title 'Distribuição semanal de uso do game - $(date)'; show title; set output '${ARQUIVOGRAFICOTEMPODISTSEM}'; plot '${ARQUIVOGNUPLOTDATA2}' using 2:xticlabels(1) notitle with boxes linecolor rgb \"gray\", '' using 0:2:2 notitle with labels font 'Verdana,7'"  &>> /dev/null; else cp "${IMAGEGRAPH0}" "${ARQUIVOGRAFICOTEMPODISTSEM}" &>> /dev/null; fi
 
   echo -ne "\b"; case "${CHARPROGRESS}" in "") CHARPROGRESS="-";; "-") CHARPROGRESS="\\";; "\\") CHARPROGRESS="|";; "|") CHARPROGRESS="/";; "/") CHARPROGRESS="-";; *) ;; esac; echo -ne "${CHARPROGRESS}"
 
-  if [ "${MAXMESANO}" -gt "0" ]; then gnuplot -p -e "set xtics font 'Verdana,10'; set yrange [0:${MAXMESANO}]; set boxwidth 0.3; set style fill solid; set terminal png size 800,600; set xtics rotate by 90 right; unset ytics; set title 'Distribuição mensal de uso do game.'; show title; set output '${ARQUIVOGRAFICOTEMPODISTMES}'; plot '${ARQUIVOGNUPLOTDATA3}' using 2:xticlabels(1) notitle with boxes linecolor rgb \"gray\", '' using 0:2:2 notitle with labels font 'Verdana,7'" &>> /dev/null; else cp "${IMAGEGRAPH0}" "${ARQUIVOGRAFICOTEMPODISTMES}" &>> /dev/null; fi
+  if [ "${MAXMESANO}" -gt "0" ]; then gnuplot -p -e "set xtics font 'Verdana,10'; set yrange [0:${MAXMESANO}]; set boxwidth 0.3; set style fill solid; set terminal png size 800,600; set xtics rotate by 90 right; unset ytics; set title 'Distribuição mensal de uso do game - $(date)'; show title; set output '${ARQUIVOGRAFICOTEMPODISTMES}'; plot '${ARQUIVOGNUPLOTDATA3}' using 2:xticlabels(1) notitle with boxes linecolor rgb \"gray\", '' using 0:2:2 notitle with labels font 'Verdana,7'" &>> /dev/null; else cp "${IMAGEGRAPH0}" "${ARQUIVOGRAFICOTEMPODISTMES}" &>> /dev/null; fi
 
   echo -ne "\b"; case "${CHARPROGRESS}" in "") CHARPROGRESS="-";; "-") CHARPROGRESS="\\";; "\\") CHARPROGRESS="|";; "|") CHARPROGRESS="/";; "/") CHARPROGRESS="-";; *) ;; esac; echo -ne "${CHARPROGRESS}"
 
-  if [ "${MAXHORADIA}" -gt "0" ]; then gnuplot -p -e "set xtics font 'Verdana,10'; set yrange [0:${MAXHORADIA}]; set boxwidth 0.3; set style fill solid; set terminal png size 800,600; set xtics rotate by 90 right; unset ytics; set title 'Distribuição horária de uso do game.'; show title; set output '${ARQUIVOGRAFICOTEMPODISTHOR}'; plot '${ARQUIVOGNUPLOTDATA4}' using 2:xticlabels(1) notitle with boxes linecolor rgb \"gray\", '' using 0:2:2 notitle with labels font 'Verdana,7'" &>> /dev/null; else cp "${IMAGEGRAPH0}" "${ARQUIVOGRAFICOTEMPODISTHOR}" &>> /dev/null; fi
+  if [ "${MAXHORADIA}" -gt "0" ]; then gnuplot -p -e "set xtics font 'Verdana,10'; set yrange [0:${MAXHORADIA}]; set boxwidth 0.3; set style fill solid; set terminal png size 800,600; set xtics rotate by 90 right; unset ytics; set title 'Distribuição horária de uso do game - $(date)'; show title; set output '${ARQUIVOGRAFICOTEMPODISTHOR}'; plot '${ARQUIVOGNUPLOTDATA4}' using 2:xticlabels(1) notitle with boxes linecolor rgb \"gray\", '' using 0:2:2 notitle with labels font 'Verdana,7'" &>> /dev/null; else cp "${IMAGEGRAPH0}" "${ARQUIVOGRAFICOTEMPODISTHOR}" &>> /dev/null; fi
 
   echo -ne "\b"; case "${CHARPROGRESS}" in "") CHARPROGRESS="-";; "-") CHARPROGRESS="\\";; "\\") CHARPROGRESS="|";; "|") CHARPROGRESS="/";; "/") CHARPROGRESS="-";; *) ;; esac; echo -ne "${CHARPROGRESS}"
 
-  if [ "${ERRMAXDIASEMANA}" -gt "0" ]; then gnuplot -p -e "set xtics font 'Verdana,10'; set yrange [0:${ERRMAXDIASEMANA}]; set boxwidth 0.3; set style fill solid; set terminal png size 800,600; set xtics rotate by 90 right; unset ytics; set title 'Distribuição semanal de erros no uso do game.'; show title; set output '${ARQUIVOGRAFICOTEMPODISTSEMERR}'; plot '${ARQUIVOGNUPLOTDATA5}' using 2:xticlabels(1) notitle with boxes linecolor rgb \"gray\", '' using 0:2:2 notitle with labels font 'Verdana,7'" &>> /dev/null; else cp "${IMAGEGRAPH0}" "${ARQUIVOGRAFICOTEMPODISTSEMERR}" &>> /dev/null; fi
+  if [ "${ERRMAXDIASEMANA}" -gt "0" ]; then gnuplot -p -e "set xtics font 'Verdana,10'; set yrange [0:${ERRMAXDIASEMANA}]; set boxwidth 0.3; set style fill solid; set terminal png size 800,600; set xtics rotate by 90 right; unset ytics; set title 'Distribuição semanal de erros no uso do game - $(date)'; show title; set output '${ARQUIVOGRAFICOTEMPODISTSEMERR}'; plot '${ARQUIVOGNUPLOTDATA5}' using 2:xticlabels(1) notitle with boxes linecolor rgb \"gray\", '' using 0:2:2 notitle with labels font 'Verdana,7'" &>> /dev/null; else cp "${IMAGEGRAPH0}" "${ARQUIVOGRAFICOTEMPODISTSEMERR}" &>> /dev/null; fi
 
   echo -ne "\b"; case "${CHARPROGRESS}" in "") CHARPROGRESS="-";; "-") CHARPROGRESS="\\";; "\\") CHARPROGRESS="|";; "|") CHARPROGRESS="/";; "/") CHARPROGRESS="-";; *) ;; esac; echo -ne "${CHARPROGRESS}"
 
-  if [ "${ERRMAXMESANO}" -gt "0" ]; then gnuplot -p -e "set xtics font 'Verdana,10'; set yrange [0:${ERRMAXMESANO}]; set boxwidth 0.3; set style fill solid; set terminal png size 800,600; set xtics rotate by 90 right; unset ytics; set title 'Distribuição mensal de erros no uso do game.'; show title; set output '${ARQUIVOGRAFICOTEMPODISTMESERR}'; plot '${ARQUIVOGNUPLOTDATA6}' using 2:xticlabels(1) notitle with boxes linecolor rgb \"gray\", '' using 0:2:2 notitle with labels font 'Verdana,7'" &>> /dev/null; else cp "${IMAGEGRAPH0}" "${ARQUIVOGRAFICOTEMPODISTMESERR}" &>> /dev/null; fi
+  if [ "${ERRMAXMESANO}" -gt "0" ]; then gnuplot -p -e "set xtics font 'Verdana,10'; set yrange [0:${ERRMAXMESANO}]; set boxwidth 0.3; set style fill solid; set terminal png size 800,600; set xtics rotate by 90 right; unset ytics; set title 'Distribuição mensal de erros no uso do game - $(date)'; show title; set output '${ARQUIVOGRAFICOTEMPODISTMESERR}'; plot '${ARQUIVOGNUPLOTDATA6}' using 2:xticlabels(1) notitle with boxes linecolor rgb \"gray\", '' using 0:2:2 notitle with labels font 'Verdana,7'" &>> /dev/null; else cp "${IMAGEGRAPH0}" "${ARQUIVOGRAFICOTEMPODISTMESERR}" &>> /dev/null; fi
 
   echo -ne "\b"; case "${CHARPROGRESS}" in "") CHARPROGRESS="-";; "-") CHARPROGRESS="\\";; "\\") CHARPROGRESS="|";; "|") CHARPROGRESS="/";; "/") CHARPROGRESS="-";; *) ;; esac; echo -ne "${CHARPROGRESS}"
 
-  if [ "${ERRMAXHORADIA}" -gt "0" ]; then gnuplot -p -e "set xtics font 'Verdana,10'; set yrange [0:${ERRMAXHORADIA}]; set boxwidth 0.3; set style fill solid; set terminal png size 800,600; set xtics rotate by 90 right; unset ytics; set title 'Distribuição horária de erros no uso do game.'; show title; set output '${ARQUIVOGRAFICOTEMPODISTHORERR}'; plot '${ARQUIVOGNUPLOTDATA7}' using 2:xticlabels(1) notitle with boxes linecolor rgb \"gray\", '' using 0:2:2 notitle with labels font 'Verdana,7'" &>> /dev/null; else cp "${IMAGEGRAPH0}" "${ARQUIVOGRAFICOTEMPODISTHORERR}" &>> /dev/null; fi
+  if [ "${ERRMAXHORADIA}" -gt "0" ]; then gnuplot -p -e "set xtics font 'Verdana,10'; set yrange [0:${ERRMAXHORADIA}]; set boxwidth 0.3; set style fill solid; set terminal png size 800,600; set xtics rotate by 90 right; unset ytics; set title 'Distribuição horária de erros no uso do game - $(date)'; show title; set output '${ARQUIVOGRAFICOTEMPODISTHORERR}'; plot '${ARQUIVOGNUPLOTDATA7}' using 2:xticlabels(1) notitle with boxes linecolor rgb \"gray\", '' using 0:2:2 notitle with labels font 'Verdana,7'" &>> /dev/null; else cp "${IMAGEGRAPH0}" "${ARQUIVOGRAFICOTEMPODISTHORERR}" &>> /dev/null; fi
 
   echo -ne "\b"; case "${CHARPROGRESS}" in "") CHARPROGRESS="-";; "-") CHARPROGRESS="\\";; "\\") CHARPROGRESS="|";; "|") CHARPROGRESS="/";; "/") CHARPROGRESS="-";; *) ;; esac; echo -ne "${CHARPROGRESS}"
 
@@ -1157,7 +1157,7 @@ if [ "${DROPBOX}" == "1" ]; then if [ "${1}" != "ne" ]; then if [ "${AVLOG}" == 
 
 # Início personalização de Antonio Vandré.
 
-# if [ "${1}" != "ne" ]; then if [ "${AVLOG}" == "1" ]; then antoniovandre_echo "Carregando no GitHub... " n; if ! cd GitHub; then mkdir GitHub; cd GitHub; fi; rm -fr antoniovandre2 &>> /dev/null; if git clone --depth 1 "https://github.com/antoniovandre2/antoniovandre2" &>> /dev/null && cp ../*_log.* antoniovandre2/antoniovandre_mathgame/ && cp ../*_log_* antoniovandre2/antoniovandre_mathgame/ && cp "../${ARQUIVOLOGTEMP}" antoniovandre2/antoniovandre_mathgame/ && cp "../${ARQUIVOCACHESTAT}" antoniovandre2/antoniovandre_mathgame/ && cd antoniovandre2 && git add antoniovandre_mathgame/* &>> /dev/null && git commit -m "Atualizando logs do AV B mathgame." &>> /dev/null && git push &>> /dev/null && cd ../../ &>> /dev/null; then echo -ne "${AV_VERDE}"; antoniovandre_echo "${SUCCESS}" n; echo -e "${AV_SEMCOR}."; else echo -ne "${AV_VERMELHO}"; bash antoniovandre_echo "${FAIL}" n; echo -ne "${AV_SEMCOR}"; echo "."; rm "${LOCKFILE}" &>> /dev/null; exit 1; fi; fi; fi
+if [ "${1}" != "ne" ]; then if [ "${AVLOG}" == "1" ]; then antoniovandre_echo "Carregando no GitHub... " n; if ! cd GitHub; then mkdir GitHub; cd GitHub; fi; rm -fr antoniovandre2 &>> /dev/null; if git clone --depth 1 "https://github.com/antoniovandre2/antoniovandre2" &>> /dev/null && cp ../*_log.* antoniovandre2/antoniovandre_mathgame/ && cp ../*_log_* antoniovandre2/antoniovandre_mathgame/ && cp "../${ARQUIVOLOGTEMP}" antoniovandre2/antoniovandre_mathgame/ && cp "../${ARQUIVOCACHESTAT}" antoniovandre2/antoniovandre_mathgame/ && cd antoniovandre2 && git add antoniovandre_mathgame/* &>> /dev/null && git commit -m "Atualizando logs do AV B mathgame." &>> /dev/null && git push &>> /dev/null && cd ../../ &>> /dev/null; then echo -ne "${AV_VERDE}"; antoniovandre_echo "${SUCCESS}" n; echo -e "${AV_SEMCOR}."; else echo -ne "${AV_VERMELHO}"; bash antoniovandre_echo "${FAIL}" n; echo -ne "${AV_SEMCOR}"; echo "."; rm "${LOCKFILE}" &>> /dev/null; exit 1; fi; fi; fi
 
 # Fim personalização de Antonio Vandré.
 
