Add files via upload

diff --git a/antoniovandre_mathgame_linux b/antoniovandre_mathgame_linux
--- a/antoniovandre_mathgame_linux
+++ b/antoniovandre_mathgame_linux
@@ -6,7 +6,7 @@
 
 # Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).
 
-# Última atualização: 28-04-2025. Não considerando alterações em variáveis globais e personalizações.
+# Última atualização: 05-05-2025. Não considerando alterações em variáveis globais e personalizações.
 
 # Argumentos: "ne" para não processar estatísticas, ou "oe" para apenas processar estatísticas.
 
@@ -222,8 +222,8 @@ NUMEROMAXIMOARGUMENTOS="10"
 MAXIMOCASASDECIMAIS="5"
 MAXMAXVALUE="1024"
 MINMAXVALUE="8"
-MAXCHAOSVALUE="50"
-MINCHAOSVALUE="10"
+MAXCHAOSVALUE="18"
+MINCHAOSVALUE="6"
 MAXTIME="60"
 MINTIME="10"
 AVSOUND="1"
@@ -305,7 +305,7 @@ antoniovandre_echo "${MATHGAME}."
 
 echo ""
 
-antoniovandre_echo "${VERSION} 28-04-2025."
+antoniovandre_echo "${VERSION} 05-05-2025."
 
 echo ""
 
@@ -424,8 +424,8 @@ while [  "${RESPOSTAUSUARIO}" != "SAIR" ] && [  "${RESPOSTAUSUARIO}" != "EXIT" ]
     "-D") if ! [ "${CASASDECIMAIS}" == "0" ]; then CASASDECIMAIS=$(echo "${CASASDECIMAIS} - 1" | bc); antoniovandre_echo "${DNOW} ${CASASDECIMAIS}."; echo "${CHAOS}%${AVTEMPO}%${LIMITETEMPO}%${MAXVALUE}%${CASASDECIMAIS}%${NUMEROARGUMENTOS}" > "${ARQUIVOOPCOES}"; FLAG="0"; else antoniovandre_echo "${DBOTTOM}"; FLAG="1"; fi; continue;;
     "+N") if [ $(echo "${MAXVALUE} * 2" | bc) -lt "${MAXMAXVALUE}" ]; then MAXVALUE=$(echo "${MAXVALUE} * 2" | bc); antoniovandre_echo "${NNOW} ${MAXVALUE}."; FLAG="0"; else antoniovandre_echo "${NOVERFLOW}"; FLAG="1"; fi; continue;;
     "-N") if [ "${MAXVALUE}" -gt "${MINMAXVALUE}" ]; then MAXVALUE=$(echo "${MAXVALUE} / 2" | bc); antoniovandre_echo "${NNOW} ${MAXVALUE}."; echo "${CHAOS}%${AVTEMPO}%${LIMITETEMPO}%${MAXVALUE}%${CASASDECIMAIS}%${NUMEROARGUMENTOS}" > "${ARQUIVOOPCOES}"; FLAG="0"; else antoniovandre_echo "${NBOTTOM}"; FLAG="1"; fi; continue;;
-    "+C") if [ $(echo "${CHAOS} + 1" | bc) -lt "${MAXCHAOSVALUE}" ]; then CHAOS=$(echo "${CHAOS} + 1" | bc); antoniovandre_echo "${CHAOSNOW} ${CHAOS}."; echo "${CHAOS}%${AVTEMPO}%${LIMITETEMPO}%${MAXVALUE}%${CASASDECIMAIS}%${NUMEROARGUMENTOS}" > "${ARQUIVOOPCOES}"; FLAG="0"; else antoniovandre_echo "${CHAOSOVERFLOW}"; FLAG="1"; fi; continue;;
-    "-C") if [ $(echo "${CHAOS} - 1" | bc) -lt "${MINCHAOSVALUE}" ]; then CHAOS=$(echo "${CHAOS} - 1" | bc); antoniovandre_echo "${CHAOSNOW} ${CHAOS}."; echo "${CHAOS}%${AVTEMPO}%${LIMITETEMPO}%${MAXVALUE}%${CASASDECIMAIS}%${NUMEROARGUMENTOS}" > "${ARQUIVOOPCOES}"; FLAG="0"; else antoniovandre_echo "${CHAOSBOTTON}"; FLAG="1"; fi; continue;;
+    "+C") if [ $(echo "${CHAOS} + 1" | bc) -le "${MAXCHAOSVALUE}" ]; then CHAOS=$(echo "${CHAOS} + 1" | bc); antoniovandre_echo "${CHAOSNOW} ${CHAOS}."; echo "${CHAOS}%${AVTEMPO}%${LIMITETEMPO}%${MAXVALUE}%${CASASDECIMAIS}%${NUMEROARGUMENTOS}" > "${ARQUIVOOPCOES}"; FLAG="0"; else antoniovandre_echo "${CHAOSOVERFLOW}"; FLAG="1"; fi; continue;;
+    "-C") if [ $(echo "${CHAOS} - 1" | bc) -ge "${MINCHAOSVALUE}" ]; then CHAOS=$(echo "${CHAOS} - 1" | bc); antoniovandre_echo "${CHAOSNOW} ${CHAOS}."; echo "${CHAOS}%${AVTEMPO}%${LIMITETEMPO}%${MAXVALUE}%${CASASDECIMAIS}%${NUMEROARGUMENTOS}" > "${ARQUIVOOPCOES}"; FLAG="0"; else antoniovandre_echo "${CHAOSBOTTOM}"; FLAG="1"; fi; continue;;
     "T") if [ "${AVTEMPO}" == "0" ]; then AVTEMPO="1"; antoniovandre_echo "${TNOW} ${AVTEMPO}."; echo "${CHAOS}%${AVTEMPO}%${LIMITETEMPO}%${MAXVALUE}%${CASASDECIMAIS}%${NUMEROARGUMENTOS}" > "${ARQUIVOOPCOES}"; else antoniovandre_echo "${TIMEALREADYACTIVATED}"; fi; FLAG="1"; continue;;
     "t") if [ "${AVTEMPO}" == "1" ]; then AVTEMPO="0"; antoniovandre_echo "${TNOW} ${AVTEMPO}."; echo "${CHAOS}%${AVTEMPO}%${LIMITETEMPO}%${MAXVALUE}%${CASASDECIMAIS}%${NUMEROARGUMENTOS}" > "${ARQUIVOOPCOES}"; else antoniovandre_echo "${TIMEALREADYDEACTIVATED}"; fi; FLAG="1"; continue;;
     "+T") if [ "${AVTEMPO}" == "1" ]; then if [ "${LIMITETEMPO}" -lt "${MAXTIME}" ]; then LIMITETEMPO=$(echo "${LIMITETEMPO} + 10" | bc); antoniovandre_echo "${TVNOW} ${LIMITETEMPO}."; echo "${CHAOS}%${AVTEMPO}%${LIMITETEMPO}%${MAXVALUE}%${CASASDECIMAIS}%${NUMEROARGUMENTOS}" > "${ARQUIVOOPCOES}"; else antoniovandre_echo "${TOVERFLOW}"; fi; else antoniovandre_echo "${TIMEDEACTIVATED}"; fi; FLAG="1"; continue;;
@@ -1152,6 +1152,12 @@ if [ "${1}" != "ne" ] && [ "${AVLOG}" == "1" ] && [ "${AVSTATS}" == "1" ] && ls 
 if [ "${AVLOG}" == "1" ] && ls "${ARQUIVOLOGTEMP}" &>> /dev/null; then bash antoniovandre_echo "${CONVLOGDOS}" n; if unix2dos "${ARQUIVOLOGTEMP}" &>> /dev/null; then echo -ne "${AV_VERDE}"; bash antoniovandre_echo "${SUCCESS}" n; echo -ne "${AV_SEMCOR}"; echo "."; else echo -ne "${AV_VERMELHO}"; bash antoniovandre_echo "${FAIL}" n; echo -ne "${AV_SEMCOR}"; echo "."; rm "${LOCKFILE}" &>> /dev/null; exit 1; fi; fi
 
 if [ "${DROPBOX}" == "1" ]; then if [ "${1}" != "ne" ]; then if [ "${AVLOG}" == "1" ]; then cp "${ARQUIVOLOGTEMP}" "${ARQUIVOLOG}" &>> /dev/null; antoniovandre_echo "${MAKINGUPLOAD}" n; if (! antoniovandre_dbxcli_put "${ARQUIVOLOG}" "${DIRCLOUDSYNC}${ARQUIVOLOG##*/}" &>> /dev/null) || (! echo -ne "1/9") || (! antoniovandre_dbxcli_put "${ARQUIVOGRAFICO}" "${DIRCLOUDSYNC}${ARQUIVOGRAFICO##*/}" &>> /dev/null) || (! echo -ne "\b\b\b2/9") || (! antoniovandre_dbxcli_put "${ARQUIVOGRAFICOPIZZA}" "${DIRCLOUDSYNC}${ARQUIVOGRAFICOPIZZA##*/}" &>> /dev/null) || (! echo -ne "\b\b\b3/9") || (! antoniovandre_dbxcli_put "${ARQUIVOGRAFICOTEMPODISTSEM}" "${DIRCLOUDSYNC}${ARQUIVOGRAFICOTEMPODISTSEM##*/}" &>> /dev/null) || (! echo -ne "\b\b\b4/9") || (! antoniovandre_dbxcli_put "${ARQUIVOGRAFICOTEMPODISTMES}" "${DIRCLOUDSYNC}${ARQUIVOGRAFICOTEMPODISTMES##*/}" &>> /dev/null) || (! echo -ne "\b\b\b5/9") || (! antoniovandre_dbxcli_put "${ARQUIVOSTATS}" "${DIRCLOUDSYNC}${ARQUIVOSTATS##*/}" &>> /dev/null) || (! echo -ne "\b\b\b6/9") || (! antoniovandre_dbxcli_put "${ARQUIVOGRAFICOTEMPODISTHOR}" "${DIRCLOUDSYNC}${ARQUIVOGRAFICOTEMPODISTHOR##*/}" &>> /dev/null) || (! echo -ne "\b\b\b7/9") || (! antoniovandre_dbxcli_put "${ARQUIVOGRAFICOTEMPODISTHORERR}" "${DIRCLOUDSYNC}${ARQUIVOGRAFICOTEMPODISTHORERR##*/}" &>> /dev/null) || (! echo -ne "\b\b\b8/9") || (! antoniovandre_dbxcli_put "${ARQUIVOGRAFICOTEMPODISTSEMERR}" "${DIRCLOUDSYNC}${ARQUIVOGRAFICOTEMPODISTSEMERR##*/}" &>> /dev/null) || (! echo -ne "\b\b\b9/9") || (! antoniovandre_dbxcli_put "${ARQUIVOGRAFICOTEMPODISTMESERR}" "${DIRCLOUDSYNC}${ARQUIVOGRAFICOTEMPODISTMESERR##*/}" &>> /dev/null) || (! echo -ne "\b\b\b\b     \b\b\b\b"); then echo -ne "${AV_VERMELHO}"; antoniovandre_echo "${ERRORUPLOADFILES}" n; echo -e "${AV_SEMCOR}."; else echo -ne "${AV_VERDE}"; antoniovandre_echo "${SUCCESS}" n; echo -e "${AV_SEMCOR}."; fi; fi; fi; fi
+
+# Início personalização de Antonio Vandré.
+
+if [ "${1}" != "ne" ]; then if [ "${AVLOG}" == "1" ]; then antoniovandre_echo "Carregando no GitHub... " n; if ! cd GitHub; then mkdir GitHub; cd GitHub; fi; rm -fr antoniovandre2 &>> /dev/null; if git clone --depth 1 "https://github.com/antoniovandre2/antoniovandre2" &>> /dev/null && cp ../*_log.* antoniovandre2/antoniovandre_mathgame/ && cp ../*_log_* antoniovandre2/antoniovandre_mathgame/ && cd antoniovandre2 && git add antoniovandre_mathgame/* &>> /dev/null && git commit -m "Atualizando logos do AV B mathgame." &>> /dev/null && git push &>> /dev/null && cd ../../ &>> /dev/null; then echo -ne "${AV_VERDE}"; antoniovandre_echo "${SUCCESS}" n; echo -e "${AV_SEMCOR}."; else echo -ne "${AV_VERMELHO}"; bash antoniovandre_echo "${FAIL}" n; echo -ne "${AV_SEMCOR}"; echo "."; rm "${LOCKFILE}" &>> /dev/null; exit 1; fi; fi; fi
+
+# Fim personalização de Antonio Vandré.
 
 antoniovandre_echo "${THANKS}"
 
